from pathlib import Path
import json,re,hashlib
R=Path(__file__).resolve().parents[1]

def text(p): return (R/p).read_text(encoding='utf-8')

def test_all():
    checks=[]
    def ck(name,cond):
        assert cond,name;checks.append(name)
    m=json.loads(text('runtime-manifest.json'))
    ck('revision4',m['release_revision']==4)
    ck('target257',m['target_version']=='2.5.7')
    ck('current255',m['expected_current_version']=='2.5.5')
    ck('r3_superseded','r3' in m['supersedes'].lower())
    a=text('payload/agent.ps1')
    ck('probe_switch_param','[switch]$StartupProbe' in a)
    ck('probe_version','STARTUP_PROBE_CAPABILITIES_VERSION' in a)
    ck('probe_json','mode="startup-probe"' in a)
    probe_block=a.split('if($StartupProbe){',1)[1].split('if($RunJobId){',1)[0]
    ck('probe_no_listener','HttpListener' not in probe_block and '.Start()' not in probe_block)
    ck('probe_before_listener',a.index('if($StartupProbe){') < a.index('$listener=New-Object Net.HttpListener'))
    ck('config_before_probe',a.index('$script:cfg=') < a.index('if($StartupProbe){'))
    ck('workspace_init_before_probe',a.index('$null=WorkspaceSummary') < a.index('if($StartupProbe){'))
    sp=text('Startup-Probe-AgentRuntime257.ps1')
    ck('probe_exec_target',"'-StartupProbe'" in sp)
    ck('probe_capture_out','-RedirectStandardOutput' in sp)
    ck('probe_capture_err','-RedirectStandardError' in sp)
    ck('probe_wait','-PassThru -Wait' in sp)
    ck('probe_temp_root','diagnostics\\startup-probes' in sp)
    ck('probe_artifact_isolated','artifact_root' in sp and "Join-Path $root 'artifacts'" in sp)
    ck('probe_no_http','Invoke-RestMethod' not in sp and 'TcpListener' not in sp and 'HttpListener' not in sp)
    stage=text('Stage-AgentRuntime257.ps1')
    ck('stage_preflight_agentmediated','-InvocationMode AgentMediated' in stage)
    ck('stage_calls_probe','Startup-Probe-AgentRuntime257.ps1' in stage)
    ck('probe_before_backup',stage.index('Startup-Probe-AgentRuntime257.ps1') < stage.index("$backup=Join-Path"))
    ck('probe_before_stage_dir',stage.index('Startup-Probe-AgentRuntime257.ps1') < stage.index("New-Item -ItemType Directory -Path $stage"))
    launch=text('Agent-Launcher.ps1')
    ck('launcher_stdout','RedirectStandardOutput' in launch)
    ck('launcher_stderr','RedirectStandardError' in launch)
    ck('launcher_exit','runtime_exit' in launch and '$p.ExitCode' in launch)
    ck('launcher_recovery','recovery_target_complete' in launch and 'rolled_back_by_launcher' in launch)
    act=text('Activate-AgentRuntime.ps1')
    ck('activation_diag','ACTIVATE_NEW_HEALTH_FAILED stderr=' in act)
    ck('activation_backup_hash','ACTIVATE_BACKUP_AGENT_HASH' in act and 'ACTIVATE_BACKUP_CAPS_HASH' in act)
    ck('activation_rollback','rollback_pass' in act and 'ROLLBACK_HEALTH_FAILED' in act)
    ck('activation_state_before_stop',act.index("state='activating'") < act.index('Stop-Process -Id $oldPid'))

    activating_line=next(x for x in act.splitlines() if "state='activating'" in x and '$state=[ordered]@{' in x)
    active_line=next(x for x in act.splitlines() if "state='active'" in x and "active_version=[string]$plan.target_version" in x and '$state=[ordered]@{' in x)
    ck('state_schema_active_version',"active_version=[string]$plan.current_version" in activating_line)
    ck('state_schema_recovered_at',"recovered_at=$null" in activating_line)
    ck('state_schema_accepted_at_initial',"accepted_at=$null" in activating_line)
    ck('state_schema_accepted_at_active',"accepted_at=$null" in active_line)
    reg=text('State-Schema-Regression257.ps1')
    ck('state_regression_shipped','state_schema_regression' in reg and 'recovered_target_files_complete' in reg)
    ck('state_regression_active_version','STATE_SCHEMA_ACTIVE_VERSION' in reg)
    ck('state_regression_runtime_exec','DUMMY257' in reg)
    ck('state_regression_mirrored',(R/'State-Schema-Regression257.ps1').read_bytes()==(R/'repo-overlay/tools/runtime/releases/2.5.7/State-Schema-Regression257.ps1').read_bytes())
    policy=json.loads(text('repo-overlay/docs/contracts/AGENT_CHANGE_EXECUTION_POLICY_V1.json'))
    ck('policy_probe_required',policy['windows_startup_probe']['required_before_activation'] is True)
    ck('policy_no_random_http',policy['windows_startup_probe']['random_httplistener_port_forbidden'] is True)
    ck('policy_logs',all(policy['runtime_launcher_logging'].values()))
    contract=text('repo-overlay/docs/contracts/AGENT_CHANGE_EXECUTION_CONTRACT_V1_FA.md')
    ck('contract_probe_barrier','Windows Target Startup-Probe Barrier' in contract)
    hand=text('HANDOFF_COMPLETE_FA.md')
    ck('handoff_r4_authorized','SOKNA-Agent-2.5.7-R4-Release.zip' in hand)
    ck('handoff_r3_forbidden',('R3' in hand and 'superseded' in hand))
    master=text('MASTER_AGENT_HANDOFF_ROADMAP_FA.md')
    ck('master_r4','Current authorized rollout candidate — R4' in master)
    ck('master_rollback_tx','rt257-1790141694403-2e4f9b9b' in master)
    caps=json.loads(text('payload/AGENT_CAPABILITIES.json'))
    ck('caps257',caps['agent']=='2.5.7')
    ck('artifact_actions',all(x in caps['actions'] for x in ['artifact.inspect','artifact.apply']))
    print(json.dumps({'ok':True,'checks':len(checks),'names':checks},separators=(',',':')))
if __name__=='__main__': test_all()
