import fs from "node:fs";
import vm from "node:vm";
import assert from "node:assert/strict";
const src=fs.readFileSync("extension/chrome/runtime_state_core.js","utf8");
const ctx={globalThis:null,Date,String};ctx.globalThis=ctx;vm.runInNewContext(src,ctx,{filename:"runtime_state_core.js"});const R=ctx.__SOKNA_RUNTIME_STATE_CORE_V1__;assert.ok(R);
let s={state:"Ready"};s={...s,...R.executionStart(s,"cmd-new","workspace.list",10)};assert.equal(s.currentCommandId,"cmd-new");assert.equal(s.executionState,"running");
s={...s,...R.deliveryUpdate(s,{recordId:"old-result",commandId:"cmd-old",deliveryState:"delivery_uncertain",uiState:"Needs Action",detail:"old delivery uncertain",actionRequired:true})};
assert.equal(s.currentCommandId,"cmd-new","older delivery must never replace the executing command id");assert.equal(s.state,"Working","execution UI must have precedence while a command is running");assert.equal(s.deliveryPendingCommandId,"cmd-old");
s={...s,...R.executionFinish(s,"cmd-new",true,"",20)};assert.equal(s.currentCommandId,"");assert.equal(s.executionState,"completed");assert.equal(s.state,"Needs Action","after execution completes, pending delivery state becomes visible");assert.equal(s.deliveryPendingCommandId,"cmd-old");
const newer={...R.executionStart(s,"cmd-next","ping",30),...s,executionState:"running",executionCurrentCommandId:"cmd-next",currentCommandId:"cmd-next",state:"Working"};
const clear=R.deliveryClear(newer,"old-result",{uiState:"Ready"});const after={...newer,...clear};assert.equal(after.currentCommandId,"cmd-next","ACK of old delivery must not clear newer execution");assert.equal(after.state,"Working");
console.log("RUNTIME_STATE_CORE_PASS");
