import fs from "node:fs";
import assert from "node:assert/strict";
const s=fs.readFileSync("extension/chrome/browser_site_capture.js","utf8");
const target=fs.readFileSync("extension/chrome/browser_target_core.js","utf8");
const ack=fs.readFileSync("extension/chrome/delivery_ack_patch.js","utf8");
const order=fs.readFileSync("extension/chrome/event_order_patch.js","utf8");
const manifest=JSON.parse(fs.readFileSync("extension/chrome/manifest.json","utf8"));
const csproj=fs.readFileSync("maintenance/Sokna.Bridge.ControlCenter/Sokna.Bridge.ControlCenter.csproj","utf8");
const iss=fs.readFileSync("installer/windows/SOKNA.Agent.iss","utf8");
assert.match(target,/browser_site_capture_core\.js/);
assert.match(target,/browser_site_capture\.js/);
assert.match(target,/delivery_ack_patch\.js/);
assert.match(target,/event_order_patch\.js/);
assert.match(s,/Math\.min\(5,cfg\.workers\)/);
assert.match(s,/captureBeyondViewport:true/);
assert.match(s,/syntheticEvidence/);
assert.match(s,/SOKNA-Bridge\/Jobs/);
assert.match(s,/sokna-browser-task-collection-v1/);
assert.match(s,/await waitTabCompleteSafe\(tab\.id/);
assert.match(s,/body_fallback_positive_ack:true/);
assert.match(ack,/body-type-id-fallback/);
assert.match(ack,/DELIVERY\.markAcknowledged/);
assert.match(order,/command-accepted/);
assert.match(order,/accepted-priority/);
for(const n of [16,32,48,128]){
  assert.equal(manifest.icons[String(n)],`icons/icon${n}.png`);
  assert.equal(manifest.action.default_icon[String(n)],`icons/icon${n}.png`);
  assert.ok(fs.existsSync(`extension/chrome/icons/icon${n}.png`));
}
assert.match(csproj,/<ApplicationIcon>sokna-bridge\.ico<\/ApplicationIcon>/);
assert.ok(fs.existsSync("maintenance/Sokna.Bridge.ControlCenter/sokna-bridge.ico"));
assert.match(iss,/SetupIconFile=sokna-bridge\.ico/);
assert.ok(fs.existsSync("installer/windows/sokna-bridge.ico"));
assert.doesNotMatch(s,/\beval\s*\(/);
assert.doesNotMatch(ack,/\beval\s*\(/);
assert.doesNotMatch(order,/\beval\s*\(/);
console.log("R13_SITE_CAPTURE_STATIC_PASS");
