import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const src=fs.readFileSync(new URL('../../extension/chrome/protocol.js',import.meta.url),'utf8');
const ctx={TextEncoder,globalThis:{}};ctx.globalThis=ctx;vm.runInNewContext(src,ctx);
const P=ctx.__SOKNA_PROTOCOL_V1__;assert.ok(P);
const b64=s=>Buffer.from(s,'utf8').toString('base64url');
const cmd={i:'nack-reg-1',o:'p',a:{}};const body=b64(JSON.stringify(cmd));
let f=P.nextV4Frame(`SOKNA4CMD:${cmd.i}:${body}:SOKNA4END`,0);
assert.equal(f.kind,'complete');assert.equal(f.validOuterId,true);assert.equal(f.hasWhitespace,false);
assert.equal(P.correlatableMalformedV4(f),true);
const malformed=`SOKNA4CMD:${cmd.i}:${body.slice(0,5)} ${body.slice(5)}:SOKNA4END`;
f=P.nextV4Frame(malformed,0);assert.equal(f.hasWhitespace,true);assert.equal(f.validOuterId,true);assert.equal(P.correlatableMalformedV4(f),true);
f=P.nextV4Frame(`SOKNA4CMD:<bad-id>:${body}:SOKNA4END`,0);assert.equal(f.validOuterId,false);assert.equal(P.correlatableMalformedV4(f),false);
const old='old-fragment-1';const good=`SOKNA4CMD:${cmd.i}:${body}:SOKNA4END`;
f=P.nextV4Frame(`SOKNA4CMD:${old}:broken historical prose ${good}`,0);assert.equal(f.kind,'nested');
f=P.nextV4Frame(`SOKNA4CMD:${old}:broken historical prose ${good}`,f.nextFrom);assert.equal(f.kind,'complete');assert.equal(f.outerId,cmd.i);
const content=fs.readFileSync(new URL('../../extension/chrome/content.js',import.meta.url),'utf8');
assert.match(content,/final:PROTO\.correlatableMalformedV4\(frame\)/);
assert.match(content,/if\(frame\.kind==="nested"\)\{from=frame\.nextFrom;continue\}/);
const bg=fs.readFileSync(new URL('../../extension/chrome/background.js',import.meta.url),'utf8');
assert.match(bg,/d\.final===true&&hard\.has\(d\.reason\)&&correlated/);
assert.match(bg,/if\(!VALID_COMMAND_ID\.test\(cid\)\)return\{ok:true,ignored:true,uncorrelated:true\}/);
console.log('TRANSPORT_V3105_REGRESSION_PASS');
