import fs from "node:fs";
import assert from "node:assert/strict";
const s=fs.readFileSync("extension/chrome/browser_site_capture.js","utf8");
const target=fs.readFileSync("extension/chrome/browser_target_core.js","utf8");
const mapSpec=fs.readFileSync("extension/chrome/browser_capture_maps.js","utf8");
const mapRun=fs.readFileSync("extension/chrome/browser_capture_map.js","utf8");
const ack=fs.readFileSync("extension/chrome/delivery_ack_patch.js","utf8");
const order=fs.readFileSync("extension/chrome/event_order_patch.js","utf8");
const manifest=JSON.parse(fs.readFileSync("extension/chrome/manifest.json","utf8"));
const csproj=fs.readFileSync("maintenance/Sokna.Bridge.ControlCenter/Sokna.Bridge.ControlCenter.csproj","utf8");
const iss=fs.readFileSync("installer/windows/SOKNA.Agent.iss","utf8");
assert.match(target,/browser_site_capture_core\.js/);
assert.match(target,/browser_site_capture\.js/);
assert.match(target,/browser_capture_maps\.js/);
assert.match(target,/browser_capture_map\.js/);
assert.match(target,/delivery_ack_patch\.js/);
assert.match(target,/event_order_patch\.js/);
assert.match(s,/Math\.min\(5,cfg\.workers\)/);
assert.match(s,/captureBeyondViewport:true/);
assert.match(s,/syntheticEvidence/);
assert.match(s,/SOKNA-Bridge\/Jobs/);
assert.match(s,/sokna-browser-task-collection-v1/);
assert.match(s,/await waitTabCompleteSafe\(tab\.id/);
assert.match(s,/body_fallback_positive_ack:true/);
assert.match(mapSpec,/local18080-ui-audit-v1/);
assert.equal((mapSpec.match(/\{"id":"[A-Z]{1,3}\d{2}"/g)||[]).length,111);
for(const id of ["S00","H09","OP12","Z90","Z91"])assert.match(mapSpec,new RegExp(`"id":"${id}"`));
assert.match(mapRun,/map_workers/);
assert.match(mapRun,/Math\.min\(5/);
assert.match(mapRun,/captureBeyondViewport:true/);
assert.match(mapRun,/state-unreached/);
assert.match(mapRun,/no-data/);
assert.match(mapRun,/preIds=new Set\(\["S00","S01","S02","S03"\]\)/);
assert.match(mapRun,/lastIds=new Set\(\["Z90","Z91"\]\)/);
assert.match(mapRun,/SOKNA-Bridge\/Jobs/);
assert.match(mapRun,/TextDecoder/);
assert.match(ack,/body-type-id-fallback/);
assert.match(ack,/DELIVERY\.markAcknowledged/);
assert.match(order,/command-accepted/);
assert.match(order,/accepted-priority/);
for(const n of [16,32,48,128]){
  assert.equal(manifest.icons[String(n)],`icons/icon${n}.png`);
  assert.equal(manifest.action.default_icon[String(n)],`icons/icon${n}.png`);
  assert.ok(fs.existsSync(`extension/chrome/icons/icon${n}.png`));
}
assert.match(csproj,/<ApplicationIcon>sokna-bridge\.ico<\/ApplicationIcon>/);
assert.ok(fs.existsSync("maintenance/Sokna.Bridge.ControlCenter/sokna-bridge.ico"));
assert.match(iss,/SetupIconFile=sokna-bridge\.ico/);
assert.ok(fs.existsSync("installer/windows/sokna-bridge.ico"));
for(const x of [s,mapRun,ack,order])assert.doesNotMatch(x,/\beval\s*\(/);
console.log("R13_SITE_CAPTURE_STATIC_PASS");
