Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'

$script:ComponentRegistryPath=$null
$script:ComponentAuditPath=$null
$script:ComponentRoot=$null
$script:ComponentTxRoot=$null
$script:AutomationRegistryPath=$null
$script:AutomationAuditPath=$null
$script:AutomationMutexName=$null

function Get-SoknaComponentOptional($Object,[string]$Name,$Default=$null){
  if($null-eq$Object){return $Default}
  try{$p=$Object.PSObject.Properties[$Name];if($null-ne$p-and$null-ne$p.Value){return $p.Value}}catch{}
  return $Default
}
function Test-SoknaComponentId([string]$Value){return ((-not[string]::IsNullOrWhiteSpace($Value))-and$Value.Length-le80-and$Value-match'^[A-Za-z0-9._-]+$')}
function Get-SoknaComponentHash([string]$Value,[int]$Length=16){
  $sha=[Security.Cryptography.SHA256]::Create();try{$b=[Text.Encoding]::UTF8.GetBytes($Value);$h=([BitConverter]::ToString($sha.ComputeHash($b))).Replace('-','').ToLowerInvariant()}finally{$sha.Dispose()}
  return $h.Substring(0,[Math]::Min($Length,$h.Length))
}
function Write-SoknaComponentJsonAtomic([string]$Path,$Object){
  $dir=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $dir)){New-Item -ItemType Directory -Path $dir -Force|Out-Null}
  $tmp=$Path+'.tmp.'+$PID+'.'+[Guid]::NewGuid().ToString('N');$Object|ConvertTo-Json -Depth 50|Set-Content -LiteralPath $tmp -Encoding UTF8;Move-Item -LiteralPath $tmp -Destination $Path -Force
}
function Test-SoknaComponentContained([string]$Root,[string]$Candidate){
  $r=[IO.Path]::GetFullPath($Root).TrimEnd('\','/');$c=[IO.Path]::GetFullPath($Candidate).TrimEnd('\','/')
  if($c.Equals($r,[StringComparison]::OrdinalIgnoreCase)){return $true};return $c.StartsWith(($r+[IO.Path]::DirectorySeparatorChar),[StringComparison]::OrdinalIgnoreCase)
}
function Assert-SoknaComponentNoReparse([string]$Path,[switch]$AllowMissing){
  $full=[IO.Path]::GetFullPath($Path);$cursor=$full
  while($true){
    if(Test-Path -LiteralPath $cursor){$item=Get-Item -LiteralPath $cursor -Force;if(($item.Attributes-band[IO.FileAttributes]::ReparsePoint)-ne0){throw 'COMPONENT_REPARSE_POINT_BLOCKED: '+$cursor}}
    elseif(-not$AllowMissing){throw 'COMPONENT_PATH_NOT_FOUND: '+$cursor}
    $parent=Split-Path -Parent $cursor;if([string]::IsNullOrWhiteSpace($parent)-or$parent-eq$cursor){break};$cursor=$parent
  }
}
function Resolve-SoknaComponentRelative([string]$Root,[string]$Relative,[switch]$AllowMissing){
  if([string]::IsNullOrWhiteSpace($Relative)-or[IO.Path]::IsPathRooted($Relative)){throw 'COMPONENT_RELATIVE_PATH_REQUIRED'}
  $full=[IO.Path]::GetFullPath((Join-Path $Root $Relative));if(-not(Test-SoknaComponentContained $Root $full)){throw 'COMPONENT_PATH_ESCAPE'};Assert-SoknaComponentNoReparse $full -AllowMissing:$AllowMissing;return $full
}
function Write-SoknaComponentAudit([string]$Action,[string]$ComponentId,$Data){
  $e=[ordered]@{schema='sokna-component-audit-v1';timestamp=(Get-Date).ToUniversalTime().ToString('o');action=$Action};if($ComponentId){$e.component_id=$ComponentId};if($Data){foreach($p in $Data.psobject.Properties){$e[$p.Name]=$p.Value}}
  $dir=Split-Path -Parent $script:ComponentAuditPath;if(-not(Test-Path -LiteralPath $dir)){New-Item -ItemType Directory -Path $dir -Force|Out-Null};Add-Content -LiteralPath $script:ComponentAuditPath -Value ($e|ConvertTo-Json -Depth 30 -Compress) -Encoding UTF8
}
function Write-SoknaAutomationAudit([string]$Action,[string]$AutomationId,$Data){
  $e=[ordered]@{schema='sokna-automation-audit-v1';timestamp=(Get-Date).ToUniversalTime().ToString('o');action=$Action};if($AutomationId){$e.automation_id=$AutomationId};if($Data){foreach($p in $Data.psobject.Properties){$e[$p.Name]=$p.Value}}
  $dir=Split-Path -Parent $script:AutomationAuditPath;if(-not(Test-Path -LiteralPath $dir)){New-Item -ItemType Directory -Path $dir -Force|Out-Null};Add-Content -LiteralPath $script:AutomationAuditPath -Value ($e|ConvertTo-Json -Depth 30 -Compress) -Encoding UTF8
}
function Convert-SoknaPropertyMap($Object){$h=[ordered]@{};if($null-ne$Object){foreach($p in $Object.psobject.Properties){$h[$p.Name]=$p.Value}};return $h}
function New-SoknaComponentRegistry(){return [ordered]@{schema='sokna-component-registry-v1';components=[ordered]@{};updated_at=(Get-Date).ToUniversalTime().ToString('o')}}
function New-SoknaAutomationRegistry(){return [ordered]@{schema='sokna-automation-registry-v1';automations=[ordered]@{};updated_at=(Get-Date).ToUniversalTime().ToString('o')}}
function Get-SoknaComponentRegistry{if(-not(Test-Path -LiteralPath $script:ComponentRegistryPath -PathType Leaf)){throw'COMPONENT_REGISTRY_MISSING'};$r=Get-Content -LiteralPath $script:ComponentRegistryPath -Raw -Encoding UTF8|ConvertFrom-Json;if([string]$r.schema-ne'sokna-component-registry-v1'){throw'COMPONENT_REGISTRY_SCHEMA_UNSUPPORTED'};return $r}
function Save-SoknaComponentRegistry($Registry){$Registry.updated_at=(Get-Date).ToUniversalTime().ToString('o');Write-SoknaComponentJsonAtomic $script:ComponentRegistryPath $Registry}
function Get-SoknaAutomationRegistry{if(-not(Test-Path -LiteralPath $script:AutomationRegistryPath -PathType Leaf)){throw'AUTOMATION_REGISTRY_MISSING'};$r=Get-Content -LiteralPath $script:AutomationRegistryPath -Raw -Encoding UTF8|ConvertFrom-Json;if([string]$r.schema-ne'sokna-automation-registry-v1'){throw'AUTOMATION_REGISTRY_SCHEMA_UNSUPPORTED'};return $r}
function Save-SoknaAutomationRegistry($Registry){$Registry.updated_at=(Get-Date).ToUniversalTime().ToString('o');Write-SoknaComponentJsonAtomic $script:AutomationRegistryPath $Registry}
function Invoke-SoknaAutomationLocked([scriptblock]$Body){
  $m=New-Object Threading.Mutex($false,$script:AutomationMutexName);$locked=$false
  try{$locked=$m.WaitOne(10000);if(-not$locked){throw'AUTOMATION_REGISTRY_LOCK_TIMEOUT'};return (& $Body)}finally{if($locked){try{$m.ReleaseMutex()}catch{}};$m.Dispose()}
}
function Initialize-SoknaComponentManager($Config,[string]$ConfigPath,[string]$RuntimeRoot){
  $configDir=Split-Path -Parent ([IO.Path]::GetFullPath($ConfigPath));$state=Join-Path $configDir 'state';$logs=Join-Path $configDir 'logs'
  $rootOverride=[string](Get-SoknaComponentOptional $Config 'component_root' '');$script:ComponentRoot=if($rootOverride){[IO.Path]::GetFullPath($rootOverride)}else{Join-Path $configDir 'components'}
  if(-not(Test-Path -LiteralPath $script:ComponentRoot)){New-Item -ItemType Directory -Path $script:ComponentRoot -Force|Out-Null};Assert-SoknaComponentNoReparse $script:ComponentRoot
  $script:ComponentRegistryPath=Join-Path $state 'components.json';$script:ComponentAuditPath=Join-Path $logs 'component-audit.jsonl';$script:ComponentTxRoot=Join-Path $state 'component-transactions'
  $script:AutomationRegistryPath=Join-Path $state 'automations.json';$script:AutomationAuditPath=Join-Path $logs 'automation-audit.jsonl';$script:AutomationMutexName='Local\SoknaAutomation-'+(Get-SoknaComponentHash $script:AutomationRegistryPath 20)
  if(-not(Test-Path -LiteralPath $script:ComponentTxRoot)){New-Item -ItemType Directory -Path $script:ComponentTxRoot -Force|Out-Null}
  if(-not(Test-Path -LiteralPath $script:ComponentRegistryPath -PathType Leaf)){Save-SoknaComponentRegistry (New-SoknaComponentRegistry)}
  if(-not(Test-Path -LiteralPath $script:AutomationRegistryPath -PathType Leaf)){Save-SoknaAutomationRegistry (New-SoknaAutomationRegistry)}
  return Get-SoknaComponentManagerStatus
}
function Get-SoknaComponentManagerStatus{
  $cr=Get-SoknaComponentRegistry;$cm=Convert-SoknaPropertyMap $cr.components;$ar=Get-SoknaAutomationRegistry;$am=Convert-SoknaPropertyMap $ar.automations
  return [ordered]@{ok=$true;schema='sokna-component-manager-status-v1';component_registry=$script:ComponentRegistryPath;component_root=$script:ComponentRoot;component_count=$cm.Count;automation_registry=$script:AutomationRegistryPath;automation_count=$am.Count;process_ownership='pid+start_time+executable+managed-sidecar';release_transaction='stage->verify->activate->health->commit; failure=>rollback';dependency_boundary='Artifact Provider + verified ArtifactRoot only';scheduler_grants='per-run job-scoped grant from non-escalating template'}
}
function Get-SoknaComponent([string]$Id){if(-not(Test-SoknaComponentId $Id)){throw'COMPONENT_ID_INVALID'};$r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;if(-not$m.Contains($Id)){throw'COMPONENT_NOT_FOUND: '+$Id};return $m[$Id]}
function Get-SoknaComponentList{$r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;$out=@();foreach($id in @($m.Keys|Sort-Object)){$out+=$m[$id]};return $out}
function Register-SoknaComponent([string]$Id,[string]$DisplayName,[string]$Type,[string]$ReleaseChannel,[string]$EntryPoint,$Args,[string]$ServiceName,[string]$HealthPath,$Dependencies){
  if(-not(Test-SoknaComponentId $Id)){throw'COMPONENT_ID_INVALID'};$kind=$Type.ToLowerInvariant();if($kind-notin@('process','service','plugin')){throw'COMPONENT_TYPE_INVALID'}
  if([string]::IsNullOrWhiteSpace($ReleaseChannel)){$ReleaseChannel='stable'};if($ReleaseChannel-notin@('stable','beta','dev','pinned')){throw'COMPONENT_RELEASE_CHANNEL_INVALID'}
  if($kind-eq'process'-and[string]::IsNullOrWhiteSpace($EntryPoint)){throw'COMPONENT_ENTRYPOINT_REQUIRED'};if($kind-eq'service'-and[string]::IsNullOrWhiteSpace($ServiceName)){throw'COMPONENT_SERVICE_NAME_REQUIRED'}
  foreach($rel in @($EntryPoint,$HealthPath)){if($rel){if([IO.Path]::IsPathRooted($rel)-or$rel-match'(^|[\\/])\.\.([\\/]|$)'){throw'COMPONENT_RELATIVE_PATH_INVALID'}}}
  $r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;if($m.Contains($Id)){throw'COMPONENT_ALREADY_EXISTS'};$now=(Get-Date).ToUniversalTime().ToString('o');$managed=Join-Path $script:ComponentRoot $Id
  if(-not(Test-Path -LiteralPath $managed)){New-Item -ItemType Directory -Path $managed -Force|Out-Null};Assert-SoknaComponentNoReparse $managed
  $deps=@();foreach($d in @($Dependencies)){if($null-eq$d){continue};$deps+=@([ordered]@{artifact_id=[string](Get-SoknaComponentOptional $d 'artifact_id' '');component_id=[string](Get-SoknaComponentOptional $d 'component_id' '');version=[string](Get-SoknaComponentOptional $d 'version' '');required=[bool](Get-SoknaComponentOptional $d 'required' $true);evidence_path=[string](Get-SoknaComponentOptional $d 'evidence_path' '');sha256=[string](Get-SoknaComponentOptional $d 'sha256' '')})}
  $c=[ordered]@{id=$Id;display_name=$(if($DisplayName){$DisplayName}else{$Id});type=$kind;install_owner='sokna-agent';managed_root=$managed;release_channel=$ReleaseChannel;entrypoint=$EntryPoint;args=@($Args);service_name=$ServiceName;health_path=$HealthPath;health_retries=5;health_delay_ms=500;dependencies=$deps;releases=[ordered]@{};active_version='';lkg_version='';state='registered';health='unknown';process=$null;created_at=$now;updated_at=$now}
  $m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;Write-SoknaComponentAudit 'component.register' $Id ([pscustomobject]@{type=$kind;release_channel=$ReleaseChannel;managed_root=$managed});return $c
}
function Set-SoknaComponentReleaseChannel([string]$Id,[string]$Channel){if($Channel-notin@('stable','beta','dev','pinned')){throw'COMPONENT_RELEASE_CHANNEL_INVALID'};$r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;if(-not$m.Contains($Id)){throw'COMPONENT_NOT_FOUND'};$c=$m[$Id];$c.release_channel=$Channel;$c.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;Write-SoknaComponentAudit 'component.channel.set' $Id ([pscustomobject]@{channel=$Channel});return $c}
function Set-SoknaComponentDependencyEvidence([string]$Id,[string]$ArtifactId,[string]$Path,[string]$Sha256){
  $r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;if(-not$m.Contains($Id)){throw'COMPONENT_NOT_FOUND'};$c=$m[$Id];$deps=@($c.dependencies);$matched=$false
  for($i=0;$i-lt$deps.Count;$i++){if([string]$deps[$i].artifact_id-eq$ArtifactId){$deps[$i].evidence_path=$Path;$deps[$i].sha256=$Sha256;$matched=$true}}
  if(-not$matched){$deps+=@([ordered]@{artifact_id=$ArtifactId;component_id='';version='';required=$true;evidence_path=$Path;sha256=$Sha256})};$c.dependencies=$deps;$c.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;Write-SoknaComponentAudit 'component.dependency.evidence' $Id ([pscustomobject]@{artifact_id=$ArtifactId;path=$Path;sha256=$Sha256});return $c
}
function Assert-SoknaComponentDependencies($Component){foreach($d in @($Component.dependencies)){if([bool]$d.required-and[string]::IsNullOrWhiteSpace([string]$d.evidence_path)-and[string]::IsNullOrWhiteSpace([string]$d.component_id)){throw'COMPONENT_REQUIRED_DEPENDENCY_MISSING: '+[string]$d.artifact_id};if([string]$d.component_id){$dc=Get-SoknaComponent ([string]$d.component_id);if([string]$dc.health-ne'healthy'){throw'COMPONENT_DEPENDENCY_UNHEALTHY: '+[string]$d.component_id}}}}
function Get-SoknaComponentReleaseRoot($Component,[string]$Version){$root=Join-Path ([string]$Component.managed_root) 'releases';$dest=Join-Path $root $Version;$full=[IO.Path]::GetFullPath($dest);if(-not(Test-SoknaComponentContained ([string]$Component.managed_root) $full)){throw'COMPONENT_RELEASE_PATH_ESCAPE'};return $full}
function Expand-SoknaComponentZip([string]$ZipPath,[string]$Destination){
  Add-Type -AssemblyName System.IO.Compression.FileSystem;$dest=[IO.Path]::GetFullPath($Destination);if(Test-Path -LiteralPath $dest){throw'COMPONENT_STAGE_EXISTS'};New-Item -ItemType Directory -Path $dest -Force|Out-Null
  $zip=[IO.Compression.ZipFile]::OpenRead($ZipPath);try{if($zip.Entries.Count-gt10000){throw'COMPONENT_ARCHIVE_TOO_MANY_ENTRIES'};[int64]$expanded=0;foreach($entry in $zip.Entries){
    $name=([string]$entry.FullName).Replace('\','/');if([string]::IsNullOrWhiteSpace($name)){continue};if($name.StartsWith('/')-or$name-match'(^|/)\.\.(/|$)'){throw'COMPONENT_ARCHIVE_PATH_ESCAPE'};$mode=([int]$entry.ExternalAttributes -shr 16)-band0xF000;if($mode-eq0xA000){throw'COMPONENT_ARCHIVE_SYMLINK_BLOCKED'}
    $expanded+=[int64]$entry.Length;if($expanded-gt8589934592){throw'COMPONENT_ARCHIVE_EXPANDED_LIMIT'};$target=[IO.Path]::GetFullPath((Join-Path $dest ($name.Replace('/',[IO.Path]::DirectorySeparatorChar))));if(-not(Test-SoknaComponentContained $dest $target)){throw'COMPONENT_ARCHIVE_PATH_ESCAPE'}
    if($name.EndsWith('/')){New-Item -ItemType Directory -Path $target -Force|Out-Null;continue};$parent=Split-Path -Parent $target;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};$src=$entry.Open();$dst=[IO.File]::Open($target,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);try{$src.CopyTo($dst)}finally{$dst.Dispose();$src.Dispose()}
  }}finally{$zip.Dispose()};Assert-SoknaComponentNoReparse $dest;return $expanded
}
function New-SoknaComponentTransaction([string]$ComponentId,[string]$From,[string]$To){$id='ctx-'+(Get-SoknaComponentHash ($ComponentId+'|'+$To+'|'+[Guid]::NewGuid().ToString('N')) 20);$tx=[ordered]@{schema='sokna-component-transaction-v1';id=$id;component_id=$ComponentId;from_version=$From;to_version=$To;state='created';events=@([ordered]@{event='created';at=(Get-Date).ToUniversalTime().ToString('o')})};Write-SoknaComponentJsonAtomic (Join-Path $script:ComponentTxRoot ($id+'.json')) $tx;return $tx}
function Update-SoknaComponentTransaction($Tx,[string]$Event,[string]$State,$Data){$Tx.state=$State;$e=[ordered]@{event=$Event;at=(Get-Date).ToUniversalTime().ToString('o')};if($Data){foreach($p in $Data.psobject.Properties){$e[$p.Name]=$p.Value}};$Tx.events+=@($e);Write-SoknaComponentJsonAtomic (Join-Path $script:ComponentTxRoot ([string]$Tx.id+'.json')) $Tx;return $Tx}
function Install-SoknaComponentRelease([string]$Id,[string]$Version,[string]$ArtifactAbsolutePath,[string]$ArtifactPath,[string]$Sha256){
  if($Version-notmatch'^[A-Za-z0-9._+-]{1,80}$'){throw'COMPONENT_VERSION_INVALID'};$c=Get-SoknaComponent $Id;Assert-SoknaComponentDependencies $c;if(-not(Test-Path -LiteralPath $ArtifactAbsolutePath -PathType Leaf)){throw'COMPONENT_ARTIFACT_MISSING'};Assert-SoknaComponentNoReparse $ArtifactAbsolutePath
  $artifactRoot=Get-SoknaArtifactRoot;if(-not(Test-SoknaComponentContained $artifactRoot $ArtifactAbsolutePath)){throw'COMPONENT_ARTIFACT_OUTSIDE_ARTIFACT_ROOT'};$sha=(Get-FileHash -LiteralPath $ArtifactAbsolutePath -Algorithm SHA256).Hash.ToLowerInvariant();if($Sha256-and$sha-ne$Sha256.ToLowerInvariant()){throw'COMPONENT_ARTIFACT_SHA256_MISMATCH'}
  $r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;$c=$m[$Id];$releases=Convert-SoknaPropertyMap $c.releases;if($releases.Contains($Version)){throw'COMPONENT_RELEASE_ALREADY_INSTALLED'};$releaseRoot=Get-SoknaComponentReleaseRoot $c $Version;$stage=Join-Path (Join-Path ([string]$c.managed_root) '.staging') ('rel-'+(Get-SoknaComponentHash ($Version+'|'+$sha) 20));if(Test-Path -LiteralPath $stage){Remove-Item -LiteralPath $stage -Recurse -Force}
  $tx=New-SoknaComponentTransaction $Id ([string]$c.active_version) $Version;try{$null=Update-SoknaComponentTransaction $tx 'stage' 'staged' ([pscustomobject]@{artifact_path=$ArtifactPath;sha256=$sha});$expanded=Expand-SoknaComponentZip $ArtifactAbsolutePath $stage;$null=Update-SoknaComponentTransaction $tx 'verify' 'verified' ([pscustomobject]@{expanded_bytes=$expanded});$parent=Split-Path -Parent $releaseRoot;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -Force|Out-Null};Move-Item -LiteralPath $stage -Destination $releaseRoot
    $releases[$Version]=[ordered]@{version=$Version;path=$releaseRoot;artifact_path=$ArtifactPath;sha256=$sha;installed_at=(Get-Date).ToUniversalTime().ToString('o');health='not_activated';transaction_id=[string]$tx.id};$c.releases=$releases;$c.state='staged';$c.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;Write-SoknaComponentAudit 'component.release.install' $Id ([pscustomobject]@{version=$Version;transaction_id=[string]$tx.id;artifact_path=$ArtifactPath;sha256=$sha});return [ordered]@{ok=$true;component=$c;transaction=$tx;release=$releases[$Version]}
  }catch{if(Test-Path -LiteralPath $stage){Remove-Item -LiteralPath $stage -Recurse -Force -ErrorAction SilentlyContinue};$null=Update-SoknaComponentTransaction $tx 'fail' 'failed' ([pscustomobject]@{error=$_.Exception.Message});Write-SoknaComponentAudit 'component.release.install.failed' $Id ([pscustomobject]@{version=$Version;transaction_id=[string]$tx.id;error=$_.Exception.Message});throw}
}
function Get-SoknaComponentProcessObservation($ProcessRecord){
  if($null-eq$ProcessRecord-or[int]$ProcessRecord.pid-le0){return $null};$p=Get-Process -Id ([int]$ProcessRecord.pid) -ErrorAction SilentlyContinue;if($null-eq$p){return $null};$exe='';try{$exe=[IO.Path]::GetFullPath([string]$p.Path)}catch{try{$exe=[IO.Path]::GetFullPath([string]$p.MainModule.FileName)}catch{}}
  $startTime=$p.StartTime.ToUniversalTime();$start=[DateTimeOffset]$startTime;$startUnixMs=$start.ToUnixTimeMilliseconds();return [ordered]@{pid=[int]$p.Id;start_unix_ms=$startUnixMs;executable=$exe;process=$p}
}
function Assert-SoknaOwnedComponentProcess($Component){
  $rec=$Component.process;if($null-eq$rec){throw'COMPONENT_PROCESS_NOT_OWNED'};$obs=Get-SoknaComponentProcessObservation $rec;if($null-eq$obs){return $null};if([int]$rec.pid-ne[int]$obs.pid-or[int64]$rec.start_unix_ms-ne[int64]$obs.start_unix_ms-or-not([string]$rec.executable).Equals([string]$obs.executable,[StringComparison]::OrdinalIgnoreCase)){throw'COMPONENT_PROCESS_OWNERSHIP_MISMATCH'}
  $side=[string]$rec.sidecar;if([string]::IsNullOrWhiteSpace($side)-or-not(Test-Path -LiteralPath $side -PathType Leaf)){throw'COMPONENT_PROCESS_OWNERSHIP_SIDECAR_MISSING'};Assert-SoknaComponentNoReparse $side;$proof=Get-Content -LiteralPath $side -Raw -Encoding UTF8|ConvertFrom-Json;if([string]$proof.owner_token-ne[string]$rec.owner_token-or[int]$proof.pid-ne[int]$rec.pid-or[int64]$proof.start_unix_ms-ne[int64]$rec.start_unix_ms){throw'COMPONENT_PROCESS_OWNERSHIP_PROOF_MISMATCH'};return $obs
}
function Get-SoknaComponentActiveRelease($Component){$v=[string]$Component.active_version;if([string]::IsNullOrWhiteSpace($v)){throw'COMPONENT_ACTIVE_RELEASE_MISSING'};$rels=Convert-SoknaPropertyMap $Component.releases;if(-not$rels.Contains($v)){throw'COMPONENT_ACTIVE_RELEASE_UNKNOWN'};return $rels[$v]}
function Quote-SoknaComponentArg([string]$Arg){if($null-eq$Arg-or$Arg.Length-eq0){return '""'};if($Arg-notmatch'[\s"]'){return $Arg};return '"'+($Arg-replace'(\\*)"','$1$1\"'-replace'(\\+)$','$1$1')+'"'}
function Start-SoknaComponent([string]$Id){
  $r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;if(-not$m.Contains($Id)){throw'COMPONENT_NOT_FOUND'};$c=$m[$Id];$kind=[string]$c.type
  if($kind-eq'plugin'){$h=Test-SoknaComponentHealth -Id $Id -Retries 1 -DelayMs 1;$c=$m[$Id];return [ordered]@{ok=$h.ok;component_id=$Id;type=$kind;plugin=$true}}
  if($kind-eq'service'){$release=Get-SoknaComponentActiveRelease $c;$svc=Get-CimInstance Win32_Service -Filter ("Name='"+([string]$c.service_name).Replace("'","''")+"'") -ErrorAction Stop;$raw=[string]$svc.PathName;$exe=if($raw.StartsWith('"')){([regex]::Match($raw,'^"([^"]+)"')).Groups[1].Value}else{($raw-split'\s+')[0]};$exe=[IO.Path]::GetFullPath($exe);if(-not(Test-SoknaComponentContained ([string]$release.path) $exe)){throw'COMPONENT_SERVICE_OWNERSHIP_MISMATCH'};Start-Service -Name ([string]$c.service_name);$c.state='running';$c.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;Write-SoknaComponentAudit 'component.start' $Id ([pscustomobject]@{type='service';service=[string]$c.service_name});return [ordered]@{ok=$true;component_id=$Id;type='service'}}
  $existing=Get-SoknaComponentProcessObservation $c.process;if($null-ne$existing){$null=Assert-SoknaOwnedComponentProcess $c;return [ordered]@{ok=$true;component_id=$Id;already_running=$true;pid=[int]$existing.pid}}
  $release=Get-SoknaComponentActiveRelease $c;$exe=Resolve-SoknaComponentRelative ([string]$release.path) ([string]$c.entrypoint);if(-not(Test-Path -LiteralPath $exe -PathType Leaf)){throw'COMPONENT_ENTRYPOINT_MISSING'};$token=[Guid]::NewGuid().ToString('N');$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$exe;$psi.WorkingDirectory=[string]$release.path;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$argv=@();foreach($a in @($c.args)){$argv+=Quote-SoknaComponentArg ([string]$a)};$psi.Arguments=($argv-join' ');$proc=New-Object Diagnostics.Process;$proc.StartInfo=$psi;[void]$proc.Start();Start-Sleep -Milliseconds 80;$start=[DateTimeOffset]$proc.StartTime.ToUniversalTime();$side=Join-Path ([string]$c.managed_root) 'process-owner.json';$proof=[ordered]@{schema='sokna-component-process-owner-v1';component_id=$Id;pid=[int]$proc.Id;start_unix_ms=$start.ToUnixTimeMilliseconds();executable=[IO.Path]::GetFullPath($exe);owner_token=$token;created_at=(Get-Date).ToUniversalTime().ToString('o')};Write-SoknaComponentJsonAtomic $side $proof;$c.process=[ordered]@{pid=$proof.pid;start_unix_ms=$proof.start_unix_ms;executable=$proof.executable;owner_token=$token;sidecar=$side};$c.state='running';$c.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;Write-SoknaComponentAudit 'component.start' $Id ([pscustomobject]@{type='process';pid=$proof.pid;version=[string]$c.active_version});return [ordered]@{ok=$true;component_id=$Id;type='process';pid=$proof.pid}
}
function Stop-SoknaComponent([string]$Id){
  $r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;if(-not$m.Contains($Id)){throw'COMPONENT_NOT_FOUND'};$c=$m[$Id];$kind=[string]$c.type
  if($kind-eq'plugin'){$c.state='stopped';$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;return [ordered]@{ok=$true;component_id=$Id;plugin=$true}}
  if($kind-eq'service'){$release=Get-SoknaComponentActiveRelease $c;$svc=Get-CimInstance Win32_Service -Filter ("Name='"+([string]$c.service_name).Replace("'","''")+"'") -ErrorAction Stop;$raw=[string]$svc.PathName;$exe=if($raw.StartsWith('"')){([regex]::Match($raw,'^"([^"]+)"')).Groups[1].Value}else{($raw-split'\s+')[0]};$exe=[IO.Path]::GetFullPath($exe);if(-not(Test-SoknaComponentContained ([string]$release.path) $exe)){throw'COMPONENT_SERVICE_OWNERSHIP_MISMATCH'};Stop-Service -Name ([string]$c.service_name) -Force;$c.state='stopped';$c.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;Write-SoknaComponentAudit 'component.stop' $Id ([pscustomobject]@{type='service'});return [ordered]@{ok=$true;component_id=$Id;type='service'}}
  $obs=$null;if($null-ne$c.process){$obs=Assert-SoknaOwnedComponentProcess $c};if($null-ne$obs){try{$obs.process.Kill()}catch{throw'COMPONENT_PROCESS_STOP_FAILED: '+$_.Exception.Message};try{$obs.process.WaitForExit(5000)|Out-Null}catch{}};$side='';if($null-ne$c.process){$side=[string]$c.process.sidecar};if($side){Remove-Item -LiteralPath $side -Force -ErrorAction SilentlyContinue};$c.process=$null;$c.state='stopped';$c.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;Write-SoknaComponentAudit 'component.stop' $Id ([pscustomobject]@{type='process'});return [ordered]@{ok=$true;component_id=$Id;type='process'}
}
function Restart-SoknaComponent([string]$Id){$null=Stop-SoknaComponent $Id;return (Start-SoknaComponent $Id)}
function Test-SoknaComponentHealth([string]$Id,[int]$Retries=5,[int]$DelayMs=500){
  $Retries=[Math]::Min([Math]::Max($Retries,1),20);$DelayMs=[Math]::Min([Math]::Max($DelayMs,1),5000);$last='unknown'
  for($i=1;$i-le$Retries;$i++){$c=Get-SoknaComponent $Id;try{$kind=[string]$c.type;if($kind-eq'process'){$obs=Assert-SoknaOwnedComponentProcess $c;if($null-eq$obs){throw'process_not_running'};$last='healthy'}elseif($kind-eq'service'){$svc=Get-Service -Name ([string]$c.service_name) -ErrorAction Stop;if([string]$svc.Status-ne'Running'){throw'service_not_running'};$last='healthy'}else{$release=Get-SoknaComponentActiveRelease $c;$hp=[string]$c.health_path;if($hp){$hf=Resolve-SoknaComponentRelative ([string]$release.path) $hp;if(-not(Test-Path -LiteralPath $hf)){throw'plugin_health_path_missing'}};$last='healthy'};break}catch{$last=$_.Exception.Message;if($i-lt$Retries){Start-Sleep -Milliseconds $DelayMs}}}
  $r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;$c=$m[$Id];$ok=($last-eq'healthy');$c.health=if($ok){'healthy'}else{'unhealthy'};$c.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;Write-SoknaComponentAudit 'component.health' $Id ([pscustomobject]@{ok=$ok;result=$last;retries=$Retries});return [ordered]@{ok=$ok;component_id=$Id;health=$c.health;detail=$last}
}
function Activate-SoknaComponentRelease([string]$Id,[string]$Version,[switch]$IsRollback){
  $r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;if(-not$m.Contains($Id)){throw'COMPONENT_NOT_FOUND'};$c=$m[$Id];$rels=Convert-SoknaPropertyMap $c.releases;if(-not$rels.Contains($Version)){throw'COMPONENT_RELEASE_NOT_INSTALLED'};$prior=[string]$c.active_version;$txId=[string]$rels[$Version].transaction_id;$txPath=Join-Path $script:ComponentTxRoot ($txId+'.json');if(-not(Test-Path -LiteralPath $txPath)){throw'COMPONENT_TRANSACTION_MISSING'};$tx=Get-Content -LiteralPath $txPath -Raw -Encoding UTF8|ConvertFrom-Json
  Assert-SoknaComponentDependencies $c;try{if($prior){try{$null=Stop-SoknaComponent $Id}catch{if($_.Exception.Message-notmatch'COMPONENT_PROCESS_NOT_OWNED'){throw}}};$r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;$c=$m[$Id];$c.active_version=$Version;$c.state='activating';$c.health='unknown';$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;$null=Update-SoknaComponentTransaction $tx 'activate' 'activated' ([pscustomobject]@{version=$Version});$null=Start-SoknaComponent $Id;$h=Test-SoknaComponentHealth -Id $Id -Retries ([int]$c.health_retries) -DelayMs ([int]$c.health_delay_ms);if(-not$h.ok){throw'COMPONENT_HEALTH_FAILED: '+[string]$h.detail};$null=Update-SoknaComponentTransaction $tx 'health_pass' 'healthy' ([pscustomobject]@{version=$Version});$r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;$c=$m[$Id];$c.lkg_version=if($IsRollback){$Version}elseif($prior){$prior}else{$Version};$c.active_version=$Version;$c.state='active';$c.health='healthy';$rels=Convert-SoknaPropertyMap $c.releases;$rel=$rels[$Version];$rel.health='healthy';$rels[$Version]=$rel;$c.releases=$rels;$m[$Id]=$c;$r.components=$m;Save-SoknaComponentRegistry $r;$null=Update-SoknaComponentTransaction $tx 'commit' 'committed' ([pscustomobject]@{lkg_version=[string]$c.lkg_version});Write-SoknaComponentAudit 'component.release.commit' $Id ([pscustomobject]@{version=$Version;lkg_version=[string]$c.lkg_version;transaction_id=$txId});return [ordered]@{ok=$true;component=$c;transaction_id=$txId}
  }catch{$failure=$_.Exception.Message;try{$null=Update-SoknaComponentTransaction $tx 'health_fail' 'failed' ([pscustomobject]@{error=$failure})}catch{};try{$current=Get-SoknaComponent $Id;if($null-ne$current.process){try{$null=Stop-SoknaComponent $Id}catch{}};$r2=Get-SoknaComponentRegistry;$m2=Convert-SoknaPropertyMap $r2.components;$cc=$m2[$Id];$cc.active_version=$prior;$cc.state='rolling_back';$cc.health='unknown';$m2[$Id]=$cc;$r2.components=$m2;Save-SoknaComponentRegistry $r2;if($prior){$null=Start-SoknaComponent $Id;$rh=Test-SoknaComponentHealth -Id $Id -Retries 5 -DelayMs 300;if(-not$rh.ok){throw'rollback_health_failed'}};$r2=Get-SoknaComponentRegistry;$m2=Convert-SoknaPropertyMap $r2.components;$cc=$m2[$Id];$cc.state=if($prior){'active'}else{'registered'};$cc.health=if($prior){'healthy'}else{'unknown'};$m2[$Id]=$cc;$r2.components=$m2;Save-SoknaComponentRegistry $r2;$null=Update-SoknaComponentTransaction $tx 'rollback' 'rolled_back' ([pscustomobject]@{restored_version=$prior});Write-SoknaComponentAudit 'component.release.rollback' $Id ([pscustomobject]@{failed_version=$Version;restored_version=$prior;error=$failure})}catch{Write-SoknaComponentAudit 'component.release.rollback.failed' $Id ([pscustomobject]@{failed_version=$Version;error=$_.Exception.Message});throw('COMPONENT_ROLLBACK_FAILED: '+$_.Exception.Message+'; original='+$failure)};throw $failure}
}
function Rollback-SoknaComponent([string]$Id){$c=Get-SoknaComponent $Id;$target=[string]$c.lkg_version;if([string]::IsNullOrWhiteSpace($target)){throw'COMPONENT_LKG_MISSING'};if($target-eq[string]$c.active_version){return [ordered]@{ok=$true;component_id=$Id;changed=$false;active_version=$target}};return (Activate-SoknaComponentRelease -Id $Id -Version $target -IsRollback)}
function Remove-SoknaComponent([string]$Id){
  $r=Get-SoknaComponentRegistry;$m=Convert-SoknaPropertyMap $r.components;if(-not$m.Contains($Id)){throw'COMPONENT_NOT_FOUND'};$c=$m[$Id];try{if(([string]$c.type -in @('process','service')) -and ([string]$c.state -ne 'registered')){$null=Stop-SoknaComponent $Id}}catch{throw'COMPONENT_REMOVE_STOP_FAILED: '+$_.Exception.Message}
  $managed=[IO.Path]::GetFullPath([string]$c.managed_root);if(-not(Test-SoknaComponentContained $script:ComponentRoot $managed)-or$managed-eq[IO.Path]::GetFullPath($script:ComponentRoot)){throw'COMPONENT_REMOVE_ESCAPE'};Assert-SoknaComponentNoReparse $managed -AllowMissing;if(Test-Path -LiteralPath $managed){Remove-Item -LiteralPath $managed -Recurse -Force};$m.Remove($Id);$r.components=$m;Save-SoknaComponentRegistry $r;Write-SoknaComponentAudit 'component.remove' $Id ([pscustomobject]@{managed_root=$managed;workspace_data_preserved=$true});return [ordered]@{ok=$true;component_id=$Id;removed=$true;workspace_data_preserved=$true}
}

function Register-SoknaAutomation([string]$Id,[string]$WorkspaceId,[string]$PlanPath,[string]$ExpectedSha256,[string]$Type,[int64]$IntervalSeconds,[string]$TriggerKey,[string]$MissedRunPolicy,[string]$ConcurrencyKey,[int]$MaxConcurrency,$GrantScopes,$GrantTools,[int]$GrantTtlSeconds,[int64]$StartUnixMs,[bool]$Enabled=$true){
  if(-not(Test-SoknaComponentId $Id)){throw'AUTOMATION_ID_INVALID'};if([string]::IsNullOrWhiteSpace($WorkspaceId)-or[string]::IsNullOrWhiteSpace($PlanPath)){throw'AUTOMATION_WORKSPACE_PLAN_REQUIRED'};$kind=$Type.ToLowerInvariant();if($kind-notin@('interval','trigger')){throw'AUTOMATION_TYPE_INVALID'};if($kind-eq'interval'-and$IntervalSeconds-lt60){throw'AUTOMATION_INTERVAL_MIN_60'};if($kind-eq'trigger'-and(-not(Test-SoknaComponentId $TriggerKey))){throw'AUTOMATION_TRIGGER_KEY_INVALID'};if($MissedRunPolicy-notin@('skip','run_once')){throw'AUTOMATION_MISSED_RUN_POLICY_INVALID'};if([string]::IsNullOrWhiteSpace($ConcurrencyKey)){$ConcurrencyKey=$Id};if($MaxConcurrency-lt1-or$MaxConcurrency-gt8){throw'AUTOMATION_CONCURRENCY_INVALID'};if($GrantTtlSeconds-lt60-or$GrantTtlSeconds-gt86400){throw'AUTOMATION_GRANT_TTL_INVALID'}
  $policy=Test-SoknaWorkspaceGrantPolicy -WorkspaceId $WorkspaceId -Scopes $GrantScopes -Tools $GrantTools;$now=[DateTimeOffset]::UtcNow;$next=0;if($kind-eq'interval'){$next=if($StartUnixMs-gt0){$StartUnixMs}else{$now.AddSeconds($IntervalSeconds).ToUnixTimeMilliseconds()}}
  return Invoke-SoknaAutomationLocked { $r=Get-SoknaAutomationRegistry;$m=Convert-SoknaPropertyMap $r.automations;if($m.Contains($Id)){throw'AUTOMATION_ALREADY_EXISTS'};$a=[ordered]@{id=$Id;workspace_id=$WorkspaceId;plan_path=$PlanPath;expected_sha256=$ExpectedSha256;type=$kind;interval_seconds=$IntervalSeconds;trigger_key=$TriggerKey;missed_run_policy=$MissedRunPolicy;concurrency_key=$ConcurrencyKey;max_concurrency=$MaxConcurrency;grant_scopes=@($policy.scopes);grant_tools=@($policy.tools);grant_ttl_seconds=$GrantTtlSeconds;enabled=$Enabled;next_run_unix_ms=$next;last_run_key='';recent_run_keys=@();pending_run_key='';pending_job_id='';pending_claimed_unix_ms=0;created_at=$now.ToString('o');updated_at=$now.ToString('o')};$m[$Id]=$a;$r.automations=$m;Save-SoknaAutomationRegistry $r;Write-SoknaAutomationAudit 'automation.register' $Id ([pscustomobject]@{type=$kind;workspace_id=$WorkspaceId;concurrency_key=$ConcurrencyKey;grant_policy='intersection'});return $a }
}
function Get-SoknaAutomationList{$r=Get-SoknaAutomationRegistry;$m=Convert-SoknaPropertyMap $r.automations;$out=@();foreach($id in @($m.Keys|Sort-Object)){$out+=$m[$id]};return $out}
function Remove-SoknaAutomation([string]$Id){return Invoke-SoknaAutomationLocked {$r=Get-SoknaAutomationRegistry;$m=Convert-SoknaPropertyMap $r.automations;if(-not$m.Contains($Id)){throw'AUTOMATION_NOT_FOUND'};$m.Remove($Id);$r.automations=$m;Save-SoknaAutomationRegistry $r;Write-SoknaAutomationAudit 'automation.remove' $Id $null;return [ordered]@{ok=$true;automation_id=$Id;removed=$true}}}
function Get-SoknaAutomationActiveCount($ActiveJobs,[string]$ConcurrencyKey){$n=0;foreach($j in @($ActiveJobs)){if(([string](Get-SoknaComponentOptional $j 'status' ''))-in@('queued','running')-and[string](Get-SoknaComponentOptional $j 'concurrency_key' '')-eq$ConcurrencyKey){$n++}};return $n}
function Add-SoknaAutomationRecentKey($Automation,[string]$RunKey){$keys=@($Automation.recent_run_keys);if($keys-notcontains$RunKey){$keys+=@($RunKey)};if($keys.Count-gt64){$keys=@($keys|Select-Object -Last 64)};$Automation.recent_run_keys=$keys;$Automation.last_run_key=$RunKey}
function Get-SoknaAutomationClaims($ActiveJobs,[int64]$NowUnixMs=0,[string]$TriggerKey='',[string]$EventId=''){
  if($NowUnixMs-le0){$NowUnixMs=[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()};if($TriggerKey-and(-not(Test-SoknaComponentId $TriggerKey))){throw'AUTOMATION_TRIGGER_KEY_INVALID'};if($TriggerKey-and(-not(Test-SoknaComponentId $EventId))){throw'AUTOMATION_EVENT_ID_INVALID'}
  return Invoke-SoknaAutomationLocked {
    $r=Get-SoknaAutomationRegistry;$m=Convert-SoknaPropertyMap $r.automations;$activeIds=@{};foreach($j in @($ActiveJobs)){if(([string](Get-SoknaComponentOptional $j 'status' ''))-in@('queued','running')){$activeIds[[string](Get-SoknaComponentOptional $j 'id' '')]=$true}}
    # Clear only stale pending claims. A two-minute grace prevents a second scheduler from racing the claim->job-write window.
    foreach($aid in @($m.Keys)){$x=$m[$aid];$pj=[string](Get-SoknaComponentOptional $x 'pending_job_id' '');[int64]$pc=[int64](Get-SoknaComponentOptional $x 'pending_claimed_unix_ms' 0);if($pj-and-not$activeIds.ContainsKey($pj)-and$pc-gt0-and($NowUnixMs-$pc)-gt120000){$x.pending_run_key='';$x.pending_job_id='';$x.pending_claimed_unix_ms=0;$m[$aid]=$x;Write-SoknaAutomationAudit 'automation.pending.recover' $aid ([pscustomobject]@{job_id=$pj})}}
    $claims=@();foreach($id in @($m.Keys|Sort-Object)){$a=$m[$id];if(-not[bool]$a.enabled){continue};$ck=[string]$a.concurrency_key;$pendingForKey=0;foreach($oid in $m.Keys){$o=$m[$oid];if([string](Get-SoknaComponentOptional $o 'concurrency_key' '')-eq$ck-and[string](Get-SoknaComponentOptional $o 'pending_run_key' '')){$pendingForKey++}};if(((Get-SoknaAutomationActiveCount $ActiveJobs $ck)+$pendingForKey)-ge[int]$a.max_concurrency){continue};$runKey='';[int64]$priorNext=[int64]$a.next_run_unix_ms
      if([string]$a.type-eq'trigger'){if(-not$TriggerKey-or[string]$a.trigger_key-ne$TriggerKey){continue};$runKey='trigger:'+$id+':'+$EventId}
      else{if($TriggerKey){continue};[int64]$due=[int64]$a.next_run_unix_ms;if($due-le0-or$NowUnixMs-lt$due){continue};[int64]$interval=[int64]$a.interval_seconds*1000;[int64]$missed=[Math]::Floor(($NowUnixMs-$due)/$interval);if($missed-gt0-and[string]$a.missed_run_policy-eq'skip'){$a.next_run_unix_ms=$due+(($missed+1)*$interval);$a.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$id]=$a;Write-SoknaAutomationAudit 'automation.missed.skip' $id ([pscustomobject]@{missed=$missed;next_run_unix_ms=$a.next_run_unix_ms});continue};$runKey='interval:'+$id+':'+$due;$a.next_run_unix_ms=$due+(($missed+1)*$interval)}
      if(@($a.recent_run_keys)-contains$runKey){continue};Add-SoknaAutomationRecentKey $a $runKey;$hash=Get-SoknaComponentHash $runKey 20;$jobId='auto-'+$id+'-'+$hash;if($jobId.Length-gt80){$jobId='auto-'+(Get-SoknaComponentHash $id 12)+'-'+$hash};$grantId='ag-'+$hash;$a.pending_run_key=$runKey;$a.pending_job_id=$jobId;$a.pending_claimed_unix_ms=$NowUnixMs;$a.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$id]=$a;$claims+=@([ordered]@{automation_id=$id;workspace_id=[string]$a.workspace_id;plan_path=[string]$a.plan_path;expected_sha256=[string]$a.expected_sha256;run_key=$runKey;job_id=$jobId;grant_id=$grantId;grant_issuer='automation:'+$id;grant_scopes=@($a.grant_scopes);grant_tools=@($a.grant_tools);grant_ttl_seconds=[int]$a.grant_ttl_seconds;concurrency_key=$ck;prior_next_run_unix_ms=$priorNext;claimed_next_run_unix_ms=[int64]$a.next_run_unix_ms})
    };$r.automations=$m;Save-SoknaAutomationRegistry $r;foreach($c in $claims){Write-SoknaAutomationAudit 'automation.claim' ([string]$c.automation_id) ([pscustomobject]@{run_key=[string]$c.run_key;job_id=[string]$c.job_id;grant_id=[string]$c.grant_id;concurrency_key=[string]$c.concurrency_key})};return $claims
  }
}
function Undo-SoknaAutomationClaim($Claim){return Invoke-SoknaAutomationLocked {$r=Get-SoknaAutomationRegistry;$m=Convert-SoknaPropertyMap $r.automations;$id=[string]$Claim.automation_id;if(-not$m.Contains($id)){return [ordered]@{ok=$true;restored=$false}};$a=$m[$id];$rk=[string]$Claim.run_key;if([string]$a.pending_run_key-ne$rk){return [ordered]@{ok=$true;restored=$false;reason='newer_claim'}};$a.recent_run_keys=@($a.recent_run_keys|Where-Object{[string]$_-ne$rk});$a.last_run_key='';$a.pending_run_key='';$a.pending_job_id='';$a.pending_claimed_unix_ms=0;if([string]$a.type-eq'interval'){$a.next_run_unix_ms=[int64]$Claim.prior_next_run_unix_ms};$a.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$id]=$a;$r.automations=$m;Save-SoknaAutomationRegistry $r;Write-SoknaAutomationAudit 'automation.claim.undo' $id ([pscustomobject]@{run_key=$rk;job_id=[string]$Claim.job_id});return [ordered]@{ok=$true;restored=$true}}}
function Complete-SoknaAutomationClaim($Claim,[string]$Status){Write-SoknaAutomationAudit 'automation.claim.submitted' ([string]$Claim.automation_id) ([pscustomobject]@{run_key=[string]$Claim.run_key;job_id=[string]$Claim.job_id;status=$Status});return [ordered]@{ok=$true;automation_id=[string]$Claim.automation_id;run_key=[string]$Claim.run_key;status=$Status}}
function Release-SoknaAutomationRun([string]$AutomationId,[string]$RunKey,[string]$JobId,[string]$Status){return Invoke-SoknaAutomationLocked {$r=Get-SoknaAutomationRegistry;$m=Convert-SoknaPropertyMap $r.automations;if(-not$m.Contains($AutomationId)){return [ordered]@{ok=$true;released=$false}};$a=$m[$AutomationId];if([string]$a.pending_run_key-eq$RunKey-and[string]$a.pending_job_id-eq$JobId){$a.pending_run_key='';$a.pending_job_id='';$a.pending_claimed_unix_ms=0;$a.updated_at=(Get-Date).ToUniversalTime().ToString('o');$m[$AutomationId]=$a;$r.automations=$m;Save-SoknaAutomationRegistry $r;Write-SoknaAutomationAudit 'automation.run.complete' $AutomationId ([pscustomobject]@{run_key=$RunKey;job_id=$JobId;status=$Status});return [ordered]@{ok=$true;released=$true}};return [ordered]@{ok=$true;released=$false;reason='claim_mismatch'}}}

Export-ModuleMember -Function Initialize-SoknaComponentManager,Get-SoknaComponentManagerStatus,Get-SoknaComponent,Get-SoknaComponentList,Register-SoknaComponent,Set-SoknaComponentReleaseChannel,Set-SoknaComponentDependencyEvidence,Install-SoknaComponentRelease,Activate-SoknaComponentRelease,Rollback-SoknaComponent,Start-SoknaComponent,Stop-SoknaComponent,Restart-SoknaComponent,Test-SoknaComponentHealth,Remove-SoknaComponent,Register-SoknaAutomation,Get-SoknaAutomationList,Remove-SoknaAutomation,Get-SoknaAutomationClaims,Undo-SoknaAutomationClaim,Complete-SoknaAutomationClaim,Release-SoknaAutomationRun
